install: npm install
script: npm test
before_install:
  - wget -qO- http://download.rethinkdb.com/apt/pubkey.gpg | sudo apt-key add -
  - sudo apt-get update
  - sudo apt-cache search rethink
  - sudo apt-get install rethinkdb